[nginx-4xx]
enabled = true
port = http,https
filter = nginx-4xx
logpath = /var/log/nginx/access.log # standard location of nginx access log, change if necessary, or use %(nginx_access_log)s
bantime = 21600
findtime = 60
maxretry = 3
